

-- SECTION 1: Exploratory Analysis SQL

USE DATABASE RETAIL_DB;
USE SCHEMA GOLD_LAYER;

-- 1. Missing Value Summary

CREATE OR REPLACE VIEW GOLD_LAYER.VW_MISSING_VALUE_SUMMARY AS
SELECT
    SUM(IFF(QUANTITY IS NULL, 1, 0))          AS MISSING_QTY,
    SUM(IFF(EXTENDED_PRICE IS NULL, 1, 0))    AS MISSING_EXT_PRICE,
    SUM(IFF(DISCOUNT IS NULL, 1, 0))          AS MISSING_DISC,
    SUM(IFF(TAX IS NULL, 1, 0))               AS MISSING_TAX,
    SUM(IFF(NET_PRICE IS NULL, 1, 0))         AS MISSING_NET_PRICE
FROM GOLD_LAYER.FACT_SALES;

-- 2. Outlier Summary

CREATE OR REPLACE VIEW GOLD_LAYER.VW_OUTLIER_SUMMARY AS
SELECT
    MIN(QUANTITY)        AS MIN_QTY,
    MAX(QUANTITY)        AS MAX_QTY,
    MIN(EXTENDED_PRICE)  AS MIN_PRICE,
    MAX(EXTENDED_PRICE)  AS MAX_PRICE,
    MIN(DISCOUNT)        AS MIN_DISC,
    MAX(DISCOUNT)        AS MAX_DISC
FROM GOLD_LAYER.FACT_SALES;



-- 3. Quantity Distribution

CREATE OR REPLACE VIEW GOLD_LAYER.VW_QUANTITY_DISTRIBUTION AS
SELECT
    QUANTITY,
    COUNT(*) AS CNT
FROM GOLD_LAYER.FACT_SALES
GROUP BY QUANTITY
ORDER BY QUANTITY;


-- 4. Discount Bucket Summary

CREATE OR REPLACE VIEW GOLD_LAYER.VW_DISCOUNT_BUCKETS AS
SELECT
    CASE 
        WHEN DISCOUNT < 0.05 THEN 'LOW'
        WHEN DISCOUNT < 0.10 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS DISCOUNT_BUCKET,
    COUNT(*) AS CNT
FROM GOLD_LAYER.FACT_SALES
GROUP BY DISCOUNT_BUCKET
ORDER BY CNT DESC;

SELECT * FROM VW_DISCOUNT_BUCKETS;

-- 5. Campaign Status (Success / Failed)

CREATE OR REPLACE VIEW GOLD_LAYER.VW_CAMPAIGN_STATUS AS
SELECT
    f.ORDER_KEY,
    f.LINE_NUMBER,
    IFF(f.SHIP_DATE_KEY <= f.RECEIPT_DATE_KEY, 'SUCCESS', 'FAILED')
        AS CAMPAIGN_STATUS,
    f.NET_PRICE,
    f.DISCOUNT,
    f.QUANTITY
FROM GOLD_LAYER.FACT_SALES f;

-- 6. Campaign Success Rate %

CREATE OR REPLACE VIEW GOLD_LAYER.VW_CAMPAIGN_SUCCESS_RATE AS
SELECT
    CAMPAIGN_STATUS,
    COUNT(*) AS TOTAL,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM GOLD_LAYER.VW_CAMPAIGN_STATUS
GROUP BY CAMPAIGN_STATUS;

-- 7. Campaign Drivers (Key behavioral metrics)

CREATE OR REPLACE VIEW GOLD_LAYER.VW_CAMPAIGN_DRIVERS AS
SELECT
    CAMPAIGN_STATUS,
    AVG(NET_PRICE) AS AVG_NET_PRICE,
    AVG(DISCOUNT)  AS AVG_DISCOUNT,
    AVG(QUANTITY)  AS AVG_QUANTITY
FROM GOLD_LAYER.VW_CAMPAIGN_STATUS
GROUP BY CAMPAIGN_STATUS;

SELECT * FROM VW_CAMPAIGN_DRIVERS;

-- 8. MONTLY ANALYSIS OF PRICING SUMMARY

-- Create the new view
CREATE OR REPLACE VIEW GOLD_LAYER.VW_MONTHLY_PRICING_SUMMARY AS
WITH yearly_max AS (
    SELECT
        d.YEAR_ AS YEAR,
        MAX(d.FULL_DATE) AS YEAR_MAX_DATE
    FROM GOLD_LAYER.FACT_SALES f
    JOIN GOLD_LAYER.DIM_DATE d
          ON f.SHIP_DATE_KEY = d.DATE_KEY
    GROUP BY d.YEAR_
),
date_windows AS (
    SELECT
        YEAR,
        DATEADD(day, -120, YEAR_MAX_DATE) AS WINDOW_START,
        DATEADD(day,  -60, YEAR_MAX_DATE) AS WINDOW_END
    FROM yearly_max
)

SELECT
    d.YEAR_ AS YEAR,
    d.MONTH_ AS MONTH,
    d.MONTH_NAME AS MONTH_NAME,
    f.RETURN_FLAG AS RETURNFLAG,
    f.LINE_STATUS AS LINESTATUS,

    SUM(f.QUANTITY) AS TOTAL_QTY,
    SUM(f.EXTENDED_PRICE) AS TOTAL_REVENUE,
    AVG(f.EXTENDED_PRICE) AS AVG_REVENUE,
    AVG(f.DISCOUNT) AS AVG_DISCOUNT,
    AVG(f.NET_PRICE) AS AVG_NET_PRICE

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY
JOIN date_windows w
      ON d.YEAR_ = w.YEAR
     AND d.FULL_DATE BETWEEN w.WINDOW_START AND w.WINDOW_END

GROUP BY 
    d.YEAR_,
    d.MONTH_,
    d.MONTH_NAME,
    f.RETURN_FLAG,
    f.LINE_STATUS

ORDER BY 
    d.YEAR_,
    d.MONTH_,
    f.RETURN_FLAG,
    f.LINE_STATUS;

SELECT * FROM VW_MONTHLY_PRICING_SUMMARY;

-- 9. View: Quarterly Pricing Analysis

CREATE OR REPLACE VIEW GOLD_LAYER.VW_QUARTERLY_PRICING AS
SELECT
    d.YEAR_,
    d.QUARTER,
    f.RETURN_FLAG AS RETURNFLAG,
    f.LINE_STATUS AS LINESTATUS,

    SUM(f.QUANTITY) AS TOTAL_QTY,
    SUM(f.EXTENDED_PRICE) AS TOTAL_REVENUE,
    AVG(f.NET_PRICE) AS AVG_NET_PRICE

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY
      
WHERE d.FULL_DATE BETWEEN '1990-01-01' AND '2000-12-31'

GROUP BY d.YEAR_, d.QUARTER, f.RETURN_FLAG, f.LINE_STATUS
ORDER BY d.YEAR_, d.QUARTER, f.RETURN_FLAG, f.LINE_STATUS;

select * from vw_quarterly_pricing;

-- 10. View: Yearly Price Trends

CREATE OR REPLACE VIEW GOLD_LAYER.VW_YEARLY_PRICE_TRENDS AS
SELECT
    d.YEAR_,
    f.RETURN_FLAG AS RETURNFLAG,

    AVG(f.NET_PRICE) AS AVG_NET_PRICE,
    AVG(f.DISCOUNT) AS AVG_DISCOUNT

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY

WHERE d.FULL_DATE BETWEEN '1990-01-01' AND '2000-12-31'

GROUP BY d.YEAR_, f.RETURN_FLAG
ORDER BY d.YEAR_, f.RETURN_FLAG;

-- 11. View: Returned Prodcut Analysis

CREATE OR REPLACE VIEW GOLD_LAYER.VW_RETURNED_PRODUCT_ANALYSIS AS
SELECT
    f.RETURN_FLAG AS RETURNFLAG,
    COUNT(*) AS TOTAL_RETURNS,
    AVG(f.NET_PRICE) AS AVG_RETURN_PRICE,
    AVG(f.DISCOUNT) AS AVG_DISCOUNT

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY

WHERE f.RETURN_FLAG = 'R'
  AND d.FULL_DATE BETWEEN '1990-01-01' AND '2000-12-31'

GROUP BY f.RETURN_FLAG
ORDER BY TOTAL_RETURNS DESC;


--12. View: Discount Effectiveness

CREATE OR REPLACE VIEW GOLD_LAYER.VW_DISCOUNT_EFFECTIVENESS AS
SELECT
    f.RETURN_FLAG AS RETURNFLAG,
    f.LINE_STATUS AS LINESTATUS,

    AVG(f.DISCOUNT) AS AVG_DISCOUNT,
    AVG(f.NET_PRICE) AS AVG_NET_PRICE,
    SUM(f.QUANTITY) AS TOTAL_QTY

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY

WHERE d.FULL_DATE BETWEEN '1990-01-01' AND '2000-12-31'

GROUP BY f.RETURN_FLAG, f.LINE_STATUS
ORDER BY f.RETURN_FLAG, f.LINE_STATUS;

--13. View: Line Item Performance Comparison

CREATE OR REPLACE VIEW GOLD_LAYER.VW_LINEITEM_PERFORMANCE AS
SELECT
    f.RETURN_FLAG AS RETURNFLAG,
    f.LINE_STATUS AS LINESTATUS,

    SUM(f.QUANTITY) AS TOTAL_QTY,
    SUM(f.EXTENDED_PRICE) AS TOTAL_REVENUE,
    AVG(f.NET_PRICE) AS AVG_NET_PRICE,
    AVG(f.DISCOUNT) AS AVG_DISCOUNT

FROM GOLD_LAYER.FACT_SALES f
JOIN GOLD_LAYER.DIM_DATE d
      ON f.SHIP_DATE_KEY = d.DATE_KEY

WHERE d.FULL_DATE BETWEEN '1990-01-01' AND '2000-12-31'

GROUP BY f.RETURN_FLAG, f.LINE_STATUS
ORDER BY f.RETURN_FLAG, f.LINE_STATUS;