
-- Bronze layer DDL and ingestion pipes
-- NOTE: Sensitive identifiers (ARNs, bucket names) are masked below.
CREATE DATABASE IF NOT EXISTS RETAIL_DB;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.BRONZE_RAW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DB.SILVER_LAYER;
USE DATABASE RETAIL_DB;
USE SCHEMA BRONZE_RAW;

-- The following environment/schema-specific selects are disabled for git
-- use schema silver_layer;
-- select * from silver_customer;


-- Infer schema command commented out to avoid exposing sample data in repo
-- SELECT *
-- FROM TABLE(INFER_SCHEMA(
--     LOCATION => '@S3_RETAIL_STAGE/raw_customer/',
--     FILE_FORMAT => 'PARQUET_FF'
-- ));

CREATE OR REPLACE FILE FORMAT PARQUET_FF
  TYPE = PARQUET;



CREATE OR REPLACE STORAGE INTEGRATION RETAIL_S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  -- Masked AWS role ARN for repository
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<MASKED_AWS_ACCOUNT>:role/<MASKED_ROLE>' -- use your aws account role
  -- Masked allowed S3 locations
  STORAGE_ALLOWED_LOCATIONS = ('s3://<MASKED_BUCKET>/parquet/'); -- use your own bucket url

DESC INTEGRATION RETAIL_S3_INT;



CREATE OR REPLACE STAGE S3_RETAIL_STAGE
  STORAGE_INTEGRATION = RETAIL_S3_INT
  -- Masked S3 bucket URL for repository
  URL = 's3://<MASKED_BUCKET>/parquet/'
  FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);

-- Listing stage contents is commented out to avoid exposing filenames/paths
-- LIST @S3_RETAIL_STAGE;

-- Informational/sample queries removed/commented before committing
-- This tells you the TRUTH right now
-- SELECT *
-- FROM TABLE(INFER_SCHEMA(
--     LOCATION => '@S3_RETAIL_STAGE/raw_customer/',
--     FILE_FORMAT => 'PARQUET_FF'
-- ));

-- SELECT * FROM CUSTOMER_RAW;
-- select * from lineitem_raw;
-- select * from supplier_raw;
-- select * from part_raw;
-- select * from partsupp_raw;
-- select * from region_raw;
-- select * from nation_raw;
-- desc pipe pipe_customer_raw;

-- Truncate commands left as-is; uncomment if intentional in your environment
truncate table customer_raw;
truncate table lineitem_raw;
truncate table supplier_raw;
truncate table part_raw;
truncate table partsupp_raw;
truncate table region_raw;
truncate table nation_raw;
truncate table orders_raw;


ALTER PIPE PIPE_CUSTOMER_RAW    REFRESH;
ALTER PIPE PIPE_LINEITEM_RAW   REFRESH;
ALTER PIPE PIPE_ORDERS_RAW     REFRESH;
ALTER PIPE PIPE_PART_RAW       REFRESH;
ALTER PIPE PIPE_PARTSUPP_RAW   REFRESH;
ALTER PIPE PIPE_SUPPLIER_RAW   REFRESH;
ALTER PIPE PIPE_NATION_RAW     REFRESH;
ALTER PIPE PIPE_REGION_RAW     REFRESH;


-- Sample stage-preview and pipe status commands commented out
-- select $1 from @S3_RETAIL_STAGE (file_format => PARQUET_FF)
-- limit 5;

-- SELECT SYSTEM$PIPE_STATUS('pipe_region_raw');

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    C_CUSTKEY     NUMBER,
    C_NAME        STRING,
    C_ADDRESS     STRING,
    C_NATIONKEY   NUMBER,
    C_PHONE       STRING,
    C_ACCTBAL     NUMBER,
    C_MKTSEGMENT  STRING,
    C_COMMENT     STRING
);

CREATE OR REPLACE PIPE PIPE_CUSTOMER_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO CUSTOMER_RAW
FROM @S3_RETAIL_STAGE/raw_customer/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);





CREATE OR REPLACE TABLE LINEITEM_RAW (
    L_ORDERKEY        NUMBER,
    L_PARTKEY         NUMBER,
    L_SUPPKEY         NUMBER,
    L_LINENUMBER      NUMBER,
    L_QUANTITY        NUMBER,
    L_EXTENDEDPRICE   NUMBER,
    L_DISCOUNT        NUMBER,
    L_TAX             NUMBER,
    L_RETURNFLAG      STRING,
    L_LINESTATUS      STRING,
    L_SHIPDATE        DATE,
    L_COMMITDATE      DATE,
    L_RECEIPTDATE     DATE,
    L_SHIPINSTRUCT    STRING,
    L_SHIPMODE        STRING,
    L_COMMENT         STRING
);

CREATE OR REPLACE PIPE PIPE_LINEITEM_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO LINEITEM_RAW
FROM @S3_RETAIL_STAGE/raw_lineitem/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);





CREATE OR REPLACE TABLE NATION_RAW (
    N_NATIONKEY  NUMBER,
    N_NAME       STRING,
    N_REGIONKEY  NUMBER,
    N_COMMENT    STRING
);

CREATE OR REPLACE PIPE PIPE_NATION_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO NATION_RAW
FROM @S3_RETAIL_STAGE/raw_nation/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);



CREATE OR REPLACE TABLE REGION_RAW (
    R_REGIONKEY NUMBER,
    R_NAME      STRING,
    R_COMMENT   STRING
);

CREATE OR REPLACE PIPE PIPE_REGION_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO REGION_RAW
FROM @S3_RETAIL_STAGE/raw_region/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);




CREATE OR REPLACE TABLE ORDERS_RAW (
    O_ORDERKEY      NUMBER,
    O_CUSTKEY       NUMBER,
    O_ORDERSTATUS   STRING,
    O_TOTALPRICE    NUMBER,
    O_ORDERDATE     DATE,
    O_ORDERPRIORITY STRING,
    O_CLERK         STRING,
    O_SHIPPRIORITY  NUMBER,
    O_COMMENT       STRING
);

CREATE OR REPLACE PIPE PIPE_ORDERS_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO ORDERS_RAW
FROM @S3_RETAIL_STAGE/raw_orders/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);




CREATE OR REPLACE TABLE PART_RAW (
    P_PARTKEY      NUMBER,
    P_NAME         STRING,
    P_MFGR         STRING,
    P_BRAND        STRING,
    P_TYPE         STRING,
    P_SIZE         NUMBER,
    P_CONTAINER    STRING,
    P_RETAILPRICE  NUMBER,
    P_COMMENT      STRING
);

CREATE OR REPLACE PIPE PIPE_PART_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO PART_RAW
FROM @S3_RETAIL_STAGE/raw_part/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);




CREATE OR REPLACE TABLE PARTSUPP_RAW (
    PS_PARTKEY     NUMBER,
    PS_SUPPKEY     NUMBER,
    PS_AVAILQTY    NUMBER,
    PS_SUPPLYCOST  NUMBER,
    PS_COMMENT     STRING
);

CREATE OR REPLACE PIPE PIPE_PARTSUPP_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO PARTSUPP_RAW
FROM @S3_RETAIL_STAGE/raw_partsupp/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);




CREATE OR REPLACE TABLE SUPPLIER_RAW (
    S_SUPPKEY   NUMBER,
    S_NAME      STRING,
    S_ADDRESS   STRING,
    S_NATIONKEY NUMBER,
    S_PHONE     STRING,
    S_ACCTBAL   NUMBER,
    S_COMMENT   STRING
);

CREATE OR REPLACE PIPE PIPE_SUPPLIER_RAW
  AUTO_INGEST = TRUE
AS
COPY INTO SUPPLIER_RAW
FROM @S3_RETAIL_STAGE/raw_supplier/
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF);



-- Drop if exists
DROP STREAM IF EXISTS CUSTOMER_BRONZE_STREAM;
DROP STREAM IF EXISTS SUPPLIER_BRONZE_STREAM;
DROP STREAM IF EXISTS PART_BRONZE_STREAM;
DROP STREAM IF EXISTS PARTSUPP_BRONZE_STREAM;
DROP STREAM IF EXISTS ORDERS_BRONZE_STREAM;
DROP STREAM IF EXISTS LINEITEM_BRONZE_STREAM;

-- Recreate streams
CREATE OR REPLACE STREAM CUSTOMER_BRONZE_STREAM  ON TABLE CUSTOMER_RAW;
CREATE OR REPLACE STREAM SUPPLIER_BRONZE_STREAM ON TABLE SUPPLIER_RAW;
CREATE OR REPLACE STREAM PART_BRONZE_STREAM     ON TABLE PART_RAW;
CREATE OR REPLACE STREAM PARTSUPP_BRONZE_STREAM ON TABLE PARTSUPP_RAW;
CREATE OR REPLACE STREAM ORDERS_BRONZE_STREAM   ON TABLE ORDERS_RAW;
CREATE OR REPLACE STREAM LINEITEM_BRONZE_STREAM ON TABLE LINEITEM_RAW;