-- 1. ENABLE TIME-TRAVEL RETENTION BY DEFAULT IT IS 1 DAY BUT SNOWFLAKE HELPS US TO STORE UPTO 90 DAYS

ALTER TABLE RETAIL_DB.BRONZE_RAW.CUSTOMER_RAW SET DATA_RETENTION_TIME_IN_DAYS = 7;
ALTER TABLE RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER SET DATA_RETENTION_TIME_IN_DAYS = 7;
ALTER TABLE RETAIL_DB.GOLD_LAYER.DIM_CUSTOMER SET DATA_RETENTION_TIME_IN_DAYS = 7;
ALTER TABLE RETAIL_DB.GOLD_LAYER.FACT_SALES SET DATA_RETENTION_TIME_IN_DAYS = 7;

-- 2. HOW TO QUERY HISTORICAL DATA (CORE TIME TRAVEL)

-- AT PARTICULAR TIMESTAMP
SELECT *
FROM GOLD_LAYER.DIM_CUSTOMER
AT (TIMESTAMP => '2025-11-30 14:00:00');

select * from gold_layer.dim_customer;
-- X HOURS AGO 

SELECT *
FROM SILVER_LAYER.SILVER_CUSTOMER
AT (OFFSET => -60*60);   -- 1 hour ago

-- USING QUERY ID

SELECT *
FROM BRONZE_RAW.CUSTOMER_RAW
BEFORE (STATEMENT => '01b45639-0001-29c3-0000-1234000193a2');


-- 3. HOW TO RESTORE A TABLE USING TIME TRAVEL

-- Restore entire table state

CREATE OR REPLACE TABLE SILVER_LAYER.SILVER_CUSTOMER 
    AS SELECT * 
    FROM SILVER_LAYER.SILVER_CUSTOMER
    AT (TIMESTAMP => '2025-01-29 14:00:00');



-- OPTIONAL BUT REQUIRED 

-- TO THE LATEST QUERY ID

SELECT QUERY_ID, QUERY_TEXT, START_TIME, END_TIME
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
WHERE QUERY_TEXT ILIKE '%DIM_CUSTOMER%'
ORDER BY START_TIME DESC;

