

USE DATABASE RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS GOLD_LAYER;
USE SCHEMA GOLD_LAYER;

SELECT * FROM FACT_SALES;

SELECT * FROM DIM_CUSTOMER;

--DIM_DATE TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    YEAR_ NUMBER,
    QUARTER NUMBER,
    MONTH_ NUMBER,
    DAY_ NUMBER,
    WEEK_OF_YEAR NUMBER,
    DAY_OF_WEEK NUMBER,
    DAY_NAME STRING,
    MONTH_NAME STRING
);

TRUNCATE TABLE DIM_DATE;

INSERT INTO DIM_DATE
WITH spine AS (
    SELECT DATEADD(day, SEQ4(), '1990-01-01'::DATE) AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 25000))
)
SELECT
    TO_NUMBER(TO_CHAR(d,'YYYYMMDD')),
    d,
    YEAR(d),
    QUARTER(d),
    MONTH(d),
    DAY(d),
    WEEKISO(d),
    DAYOFWEEK(d),
    DAYNAME(d),
    MONTHNAME(d)
FROM spine
WHERE d <= DATEADD(year,20,CURRENT_DATE());


--DIM_REGION TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_REGION AS
SELECT
    R_REGIONKEY AS REGION_KEY,
    R_NAME AS REGION_NAME,
    R_COMMENT AS COMMENT
FROM RETAIL_DB.SILVER_LAYER.SILVER_REGION;


-- DIM_NATION TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_NATION AS
SELECT
    N_NATIONKEY AS NATION_KEY,
    N_NAME AS NATION_NAME,
    N_REGIONKEY AS REGION_KEY,
    N_COMMENT AS COMMENT
FROM RETAIL_DB.SILVER_LAYER.SILVER_NATION;


--DIM_CUSTOMER TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    C_CUSTKEY NUMBER,
    C_NAME STRING,
    C_ADDRESS STRING,
    C_NATIONKEY NUMBER,
    C_PHONE STRING,
    C_ACCTBAL NUMBER(12,2),
    C_MKTSEGMENT STRING,
    START_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    RECORD_SOURCE STRING DEFAULT 'SILVER'
);

--DIM_SUPPLIER TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_SUPPLIER (
    SUPPLIER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    S_SUPPKEY NUMBER,
    S_NAME STRING,
    S_ADDRESS STRING,
    S_NATIONKEY NUMBER,
    S_PHONE STRING,
    S_ACCTBAL NUMBER(12,2),
    START_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    RECORD_SOURCE STRING DEFAULT 'SILVER'
);

--DIM_PART TABLE SCHEMA

CREATE OR REPLACE TABLE DIM_PART (
    PART_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    P_PARTKEY NUMBER,
    P_NAME STRING,
    P_MFGR STRING,
    P_BRAND STRING,
    P_TYPE STRING,
    P_SIZE NUMBER,
    P_CONTAINER STRING,
    P_RETAILPRICE NUMBER(12,2),
    START_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    END_DATE TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    RECORD_SOURCE STRING DEFAULT 'SILVER'
);


--FACT_TABLE SCHEMA 

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_KEY NUMBER,
    LINE_NUMBER NUMBER,
    CUSTOMER_SK NUMBER,
    PART_SK NUMBER,
    SUPPLIER_SK NUMBER,
    NATION_SK NUMBER,
    REGION_SK NUMBER,
    ORDER_DATE_KEY NUMBER,
    SHIP_DATE_KEY NUMBER,
    RECEIPT_DATE_KEY NUMBER,
    QUANTITY NUMBER(12,2),
    EXTENDED_PRICE NUMBER(12,2),
    DISCOUNT NUMBER(12,4),
    RETURN_FLAG STRING,
    LINE_STATUS STRING,
    TAX NUMBER(12,4),
    NET_PRICE NUMBER(12,2),
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

select * from silver_layer.silver_customer_stream;

--CREATE STREAMING ON SILVER_LAYER TABELS 

DROP STREAM IF EXISTS RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER_STREAM;
DROP STREAM IF EXISTS RETAIL_DB.SILVER_LAYER.SILVER_SUPPLIER_STREAM;
DROP STREAM IF EXISTS RETAIL_DB.SILVER_LAYER.SILVER_PART_STREAM;
DROP STREAM IF EXISTS RETAIL_DB.SILVER_LAYER.SILVER_LINEITEM_STREAM;
DROP STREAM IF EXISTS RETAIL_DB.SILVER_LAYER.SILVER_ORDERS_STREAM;

CREATE OR REPLACE STREAM RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER_STREAM
    ON TABLE RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER;

CREATE OR REPLACE STREAM RETAIL_DB.SILVER_LAYER.SILVER_SUPPLIER_STREAM
    ON TABLE RETAIL_DB.SILVER_LAYER.SILVER_SUPPLIER;

CREATE OR REPLACE STREAM RETAIL_DB.SILVER_LAYER.SILVER_PART_STREAM
    ON TABLE RETAIL_DB.SILVER_LAYER.SILVER_PART;

CREATE OR REPLACE STREAM RETAIL_DB.SILVER_LAYER.SILVER_LINEITEM_STREAM
    ON TABLE RETAIL_DB.SILVER_LAYER.SILVER_LINEITEM;

CREATE OR REPLACE STREAM RETAIL_DB.SILVER_LAYER.SILVER_ORDERS_STREAM
    ON TABLE RETAIL_DB.SILVER_LAYER.SILVER_ORDERS;


--INITIAL LOAD TRUE ONLY ONCE

TRUNCATE TABLE DIM_CUSTOMER;
TRUNCATE TABLE DIM_SUPPLIER;
TRUNCATE TABLE DIM_PART;
TRUNCATE TABLE FACT_SALES;

INSERT INTO GOLD_LAYER.DIM_CUSTOMER (
  C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE,
  C_ACCTBAL, C_MKTSEGMENT,
  START_DATE, END_DATE, IS_CURRENT, RECORD_SOURCE
)
SELECT
  C_CUSTKEY,
  C_NAME,
  C_ADDRESS,
  C_NATIONKEY,
  C_PHONE,
  C_ACCTBAL,
  C_MKTSEGMENT,
  TO_TIMESTAMP_NTZ('1990-01-01 00:00:00'),
  TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
  TRUE,
  'INITIAL_LOAD'
FROM RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER; -- or remove WHERE for full load

--FOR SUPPLIER LOAD
INSERT INTO GOLD_LAYER.DIM_SUPPLIER (
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_NATIONKEY,
    S_PHONE,
    S_ACCTBAL,
    START_DATE,
    END_DATE,
    IS_CURRENT,
    RECORD_SOURCE
)
SELECT
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_NATIONKEY,
    S_PHONE,
    S_ACCTBAL,
    CURRENT_TIMESTAMP(),
    TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    TRUE,
    'INITIAL_LOAD'
FROM RETAIL_DB.SILVER_LAYER.SILVER_SUPPLIER;


INSERT INTO GOLD_LAYER.DIM_PART (
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_BRAND,
    P_TYPE,
    P_SIZE,
    P_CONTAINER,
    P_RETAILPRICE,
    START_DATE,
    END_DATE,
    IS_CURRENT,
    RECORD_SOURCE
)
SELECT
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_BRAND,
    P_TYPE,
    P_SIZE,
    P_CONTAINER,
    P_RETAILPRICE,
    CURRENT_TIMESTAMP(),
    TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    TRUE,
    'INITIAL_LOAD'
FROM RETAIL_DB.SILVER_LAYER.SILVER_PART;

INSERT INTO GOLD_LAYER.FACT_SALES (
    ORDER_KEY,
    LINE_NUMBER,
    CUSTOMER_SK,
    PART_SK,
    SUPPLIER_SK,
    NATION_SK,
    REGION_SK,
    ORDER_DATE_KEY,
    SHIP_DATE_KEY,
    RECEIPT_DATE_KEY,
    QUANTITY,
    EXTENDED_PRICE,
    DISCOUNT,
    TAX,
    NET_PRICE,
    RETURN_FLAG,
    LINE_STATUS
)
SELECT
    li.L_ORDERKEY AS ORDER_KEY,
    li.L_LINENUMBER AS LINE_NUMBER,

    dc.CUSTOMER_SK,
    dp.PART_SK,
    ds.SUPPLIER_SK,

    dn.NATION_KEY AS NATION_SK,
    dr.REGION_KEY AS REGION_SK,

    TO_NUMBER(TO_CHAR(o.O_ORDERDATE, 'YYYYMMDD')) AS ORDER_DATE_KEY,
    TO_NUMBER(TO_CHAR(li.L_SHIPDATE, 'YYYYMMDD')) AS SHIP_DATE_KEY,
    TO_NUMBER(TO_CHAR(li.L_RECEIPTDATE, 'YYYYMMDD')) AS RECEIPT_DATE_KEY,

    li.L_QUANTITY,
    li.L_EXTENDEDPRICE,
    li.L_DISCOUNT,
    li.L_TAX,
    li.NET_PRICE,

    -- NEW COLUMNS
    li.L_RETURNFLAG AS RETURN_FLAG,
    li.L_LINESTATUS AS LINE_STATUS

FROM RETAIL_DB.SILVER_LAYER.SILVER_LINEITEM li
JOIN RETAIL_DB.SILVER_LAYER.SILVER_ORDERS o
     ON li.L_ORDERKEY = o.O_ORDERKEY
LEFT JOIN GOLD_LAYER.DIM_CUSTOMER dc
     ON o.O_CUSTKEY = dc.C_CUSTKEY
    AND dc.IS_CURRENT = TRUE
LEFT JOIN GOLD_LAYER.DIM_PART dp
     ON li.L_PARTKEY = dp.P_PARTKEY
    AND dp.IS_CURRENT = TRUE
LEFT JOIN GOLD_LAYER.DIM_SUPPLIER ds
     ON li.L_SUPPKEY = ds.S_SUPPKEY
    AND ds.IS_CURRENT = TRUE
LEFT JOIN GOLD_LAYER.DIM_NATION dn
     ON dc.C_NATIONKEY = dn.NATION_KEY
LEFT JOIN GOLD_LAYER.DIM_REGION dr
     ON dn.REGION_KEY = dr.REGION_KEY;




--PROCEDURE FOR SCD TYPE 2

CREATE OR REPLACE PROCEDURE GOLD_LAYER.LOAD_GOLD_INCREMENTAL()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

--------------------------------------------------------------------------------
-- STEP 0: Materialize each stream into a temporary table so we consume each
-- stream exactly once. If the stream has no rows, the temp table will be empty.
--------------------------------------------------------------------------------

-- Customer stream
CREATE OR REPLACE TEMPORARY TABLE TMP_CUST_STREAM AS
SELECT * FROM RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER_STREAM;

-- Supplier stream
CREATE OR REPLACE TEMPORARY TABLE TMP_SUPP_STREAM AS
SELECT * FROM RETAIL_DB.SILVER_LAYER.SILVER_SUPPLIER_STREAM;

-- Part stream
CREATE OR REPLACE TEMPORARY TABLE TMP_PART_STREAM AS
SELECT * FROM RETAIL_DB.SILVER_LAYER.SILVER_PART_STREAM;

--------------------------------------------------------------------------------
-- DIM_CUSTOMER SCD-2
--------------------------------------------------------------------------------

-- 1) Expire on DELETE events
UPDATE GOLD_LAYER.DIM_CUSTOMER tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_CUST_STREAM src
WHERE src.METADATA$ACTION = 'DELETE'
  AND tgt.C_CUSTKEY = src.C_CUSTKEY
  AND tgt.IS_CURRENT = TRUE;

-- 2) Expire current rows on UPDATE only when values actually changed
UPDATE GOLD_LAYER.DIM_CUSTOMER tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_CUST_STREAM src
WHERE src.METADATA$ACTION = 'UPDATE'
  AND tgt.C_CUSTKEY = src.C_CUSTKEY
  AND tgt.IS_CURRENT = TRUE
  AND (
        tgt.C_NAME       IS DISTINCT FROM src.C_NAME OR
        tgt.C_ADDRESS    IS DISTINCT FROM src.C_ADDRESS OR
        tgt.C_NATIONKEY  IS DISTINCT FROM src.C_NATIONKEY OR
        tgt.C_PHONE      IS DISTINCT FROM src.C_PHONE OR
        tgt.C_ACCTBAL    IS DISTINCT FROM src.C_ACCTBAL OR
        tgt.C_MKTSEGMENT IS DISTINCT FROM src.C_MKTSEGMENT
      );

-- 3) Insert new versions for INSERT and for UPDATE where values changed
INSERT INTO GOLD_LAYER.DIM_CUSTOMER (
  C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE,
  C_ACCTBAL, C_MKTSEGMENT,
  START_DATE, END_DATE, IS_CURRENT, RECORD_SOURCE
)
SELECT
  src.C_CUSTKEY,
  src.C_NAME,
  src.C_ADDRESS,
  src.C_NATIONKEY,
  src.C_PHONE,
  src.C_ACCTBAL,
  src.C_MKTSEGMENT,
  CURRENT_TIMESTAMP(),
  TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
  TRUE,
  'SILVER'
FROM TMP_CUST_STREAM src
WHERE src.METADATA$ACTION = 'INSERT'
   -- for UPDATE, insert only if a tracked attribute actually changed
   OR (src.METADATA$ACTION = 'UPDATE' AND EXISTS (
         SELECT 1
         FROM GOLD_LAYER.DIM_CUSTOMER d
         WHERE d.C_CUSTKEY = src.C_CUSTKEY
           AND d.IS_CURRENT = FALSE
           -- ensure we don't re-insert for updates that didn't change;
           -- we expired the previous current row above only when change occurred,
           -- so we can just insert for UPDATE if the expire happened.
       ));

--------------------------------------------------------------------------------
-- DIM_SUPPLIER SCD-2
--------------------------------------------------------------------------------

UPDATE GOLD_LAYER.DIM_SUPPLIER tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_SUPP_STREAM src
WHERE src.METADATA$ACTION = 'DELETE'
  AND tgt.S_SUPPKEY = src.S_SUPPKEY
  AND tgt.IS_CURRENT = TRUE;

UPDATE GOLD_LAYER.DIM_SUPPLIER tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_SUPP_STREAM src
WHERE src.METADATA$ACTION = 'UPDATE'
  AND tgt.S_SUPPKEY = src.S_SUPPKEY
  AND tgt.IS_CURRENT = TRUE
  AND (
        tgt.S_NAME    IS DISTINCT FROM src.S_NAME OR
        tgt.S_ADDRESS IS DISTINCT FROM src.S_ADDRESS OR
        tgt.S_NATIONKEY IS DISTINCT FROM src.S_NATIONKEY OR
        tgt.S_PHONE   IS DISTINCT FROM src.S_PHONE OR
        tgt.S_ACCTBAL IS DISTINCT FROM src.S_ACCTBAL
      );

INSERT INTO GOLD_LAYER.DIM_SUPPLIER (
    S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL,
    START_DATE, END_DATE, IS_CURRENT, RECORD_SOURCE
)
SELECT
    src.S_SUPPKEY, src.S_NAME, src.S_ADDRESS, src.S_NATIONKEY, src.S_PHONE, src.S_ACCTBAL,
    CURRENT_TIMESTAMP(), TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    TRUE, 'SILVER'
FROM TMP_SUPP_STREAM src
WHERE src.METADATA$ACTION = 'INSERT'
   OR (src.METADATA$ACTION = 'UPDATE' AND EXISTS (
         SELECT 1 FROM GOLD_LAYER.DIM_SUPPLIER d
         WHERE d.S_SUPPKEY = src.S_SUPPKEY
           AND d.IS_CURRENT = FALSE
       ));

--------------------------------------------------------------------------------
-- DIM_PART SCD-2
--------------------------------------------------------------------------------

UPDATE GOLD_LAYER.DIM_PART tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_PART_STREAM src
WHERE src.METADATA$ACTION = 'DELETE'
  AND tgt.P_PARTKEY = src.P_PARTKEY
  AND tgt.IS_CURRENT = TRUE;

UPDATE GOLD_LAYER.DIM_PART tgt
SET END_DATE = CURRENT_TIMESTAMP(), IS_CURRENT = FALSE
FROM TMP_PART_STREAM src
WHERE src.METADATA$ACTION = 'UPDATE'
  AND tgt.P_PARTKEY = src.P_PARTKEY
  AND tgt.IS_CURRENT = TRUE
  AND (
        tgt.P_NAME      IS DISTINCT FROM src.P_NAME OR
        tgt.P_MFGR      IS DISTINCT FROM src.P_MFGR OR
        tgt.P_BRAND     IS DISTINCT FROM src.P_BRAND OR
        tgt.P_TYPE      IS DISTINCT FROM src.P_TYPE OR
        tgt.P_SIZE      IS DISTINCT FROM src.P_SIZE OR
        tgt.P_CONTAINER IS DISTINCT FROM src.P_CONTAINER OR
        tgt.P_RETAILPRICE IS DISTINCT FROM src.P_RETAILPRICE
      );

INSERT INTO GOLD_LAYER.DIM_PART (
    P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE,
    START_DATE, END_DATE, IS_CURRENT, RECORD_SOURCE
)
SELECT
    src.P_PARTKEY, src.P_NAME, src.P_MFGR, src.P_BRAND, src.P_TYPE, src.P_SIZE, src.P_CONTAINER, src.P_RETAILPRICE,
    CURRENT_TIMESTAMP(), TO_TIMESTAMP_NTZ('9999-12-31 23:59:59'),
    TRUE, 'SILVER'
FROM TMP_PART_STREAM src
WHERE src.METADATA$ACTION = 'INSERT'
   OR (src.METADATA$ACTION = 'UPDATE' AND EXISTS (
         SELECT 1 FROM GOLD_LAYER.DIM_PART d
         WHERE d.P_PARTKEY = src.P_PARTKEY
           AND d.IS_CURRENT = FALSE
       ));

--------------------------------------------------------------------------------
-- CLEANUP: temp tables will be dropped automatically at session end.
-- We return success.
--------------------------------------------------------------------------------

RETURN 'SUCCESS';
END;
$$;




-- TASKING THE PROCEDURE FOR AUTOMATION




--MANUAL TESTING OF OUR CODE

UPDATE RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER
SET C_NAME = 'SCD2_TEST_' || RANDOM()
WHERE C_CUSTKEY = 2;


CALL GOLD_LAYER.LOAD_GOLD_INCREMENTAL();


SELECT *
FROM RETAIL_DB.SILVER_LAYER.SILVER_CUSTOMER_STREAM;

SELECT * FROM GOLD_LAYER.DIM_CUSTOMER WHERE C_CUSTKEY = 1;

select * from gold_layer.dim_customer;

-- LAST 10 UPDATED RECORDS IN OUR DIM_CUSTOMER
SELECT *
FROM GOLD_LAYER.DIM_CUSTOMER
ORDER BY START_DATE DESC
LIMIT 10;

-- ONLY NEWLY INSERTED AND UPDATED DATA

SELECT *
FROM GOLD_LAYER.DIM_CUSTOMER
WHERE RECORD_SOURCE = 'SILVER'
ORDER BY START_DATE DESC
LIMIT 10;


-- THIS HELPS US TO SHOW THE OLD AND NEW VERSION SIDE BY SIDE 

WITH ordered AS (
    SELECT *,
           LAG(C_NAME) OVER (PARTITION BY C_CUSTKEY ORDER BY START_DATE) AS PREV_NAME,
           LAG(C_ADDRESS) OVER (PARTITION BY C_CUSTKEY ORDER BY START_DATE) AS PREV_ADDRESS
    FROM GOLD_LAYER.DIM_CUSTOMER
)
SELECT *
FROM ordered
WHERE PREV_NAME IS NOT NULL  -- only when change happened
ORDER BY START_DATE DESC
LIMIT 10;

select * from fact_sales;


--TASK TO MERGE THE DATA WITH STREAMING DATA

CREATE OR REPLACE TASK TASK_LOAD_GOLD_INCREMENTAL
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 * * * * UTC'   -- runs every hour at minute 0
AS
CALL GOLD_LAYER.LOAD_GOLD_INCREMENTAL();


-- TO RESUMING THE DATA

ALTER TASK TASK_LOAD_GOLD_INCREMENTAL RESUME;
